const commanders = [
  {
    type: 'group', name: 'Neutral', items: [
    { name: "Ramsay Snow", subName: "The Bastard of Bolton", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Neutral/Commander-Cards/20402f.jpg", token: "./Images/Neutral/Tokens/ASOIAF-NEUTRAL-RAMSAY.png", tactics1: "./Images/Tactics/40408.jpg", tactics2: "./Images/Tactics/40409.jpg", tactics3: "./Images/Tactics/40410.jpg", attachment2: {name: "Reek", cost: 0, type: "Infantry", unique: true, imgFile: "./Images/Neutral/Attachment-Cards/20404f.jpg"}, neutral: true },
    { name: "Roose Bolton", subName: "Lord of the Dreadfort", cost: 0, type: "NCU", unique: true, commander: true, imgFile: "./Images/Neutral/Commander-Cards/30401f.jpg", token: "./Images/Neutral/Tokens/ASOIAF-NEUTRAL-ROOSE.png", tactics1: "./Images/Tactics/40411.jpg", tactics2: "./Images/Tactics/40412.jpg", tactics3: "./Images/Tactics/40413.jpg", attachment2: "None", neutral: true },
    { name: "Vargo Hoat", subName: "The Goat of Harrenhal", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Neutral/Commander-Cards/20409f.jpg", token: "./Images/Neutral/Tokens/ASOIAF-NEUTRAL-VARGO.png", tactics1: "./Images/Tactics/40414.jpg", tactics2: "./Images/Tactics/40415.jpg", tactics3: "./Images/Tactics/40416.jpg", attachment2: "None", neutral: true },
    { name: "Daario Naharis", subName: "Stormcrow Captain", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Neutral/Commander-Cards/20411f.jpg", token: "./Images/Neutral/Tokens/ASOIAF-NEUTRAL-DAARIO.png", tactics1: "./Images/Tactics/40417.jpg", tactics2: "./Images/Tactics/40418.jpg", tactics3: "./Images/Tactics/40419.jpg", attachment2: "None", neutral: true }
    ]
  },
  {
    type: 'group', name: 'Lannister', items: [
    { name: "Gregor Clegane", subName: "The Mountain", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Lannister/Commander-Cards/20116f.jpg", thumb: "./Images/Lannister/Thumb/P-20116b.png", tactics1: "./Images/Tactics/40108.jpg", tactics2: "./Images/Tactics/40109.jpg", tactics3: "./Images/Tactics/40110.jpg", token: "./Images/Lannister/Tokens/ASOIAF-LANNISTER-ATCH-C-THEMTN.png", attachment2: "None" },
    { name: "Jaime Lannister", subName: "The Kingslayer", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Lannister/Commander-Cards/20115f.jpg",thumb: "./Images/Lannister/Thumb/P-20115b.png", tactics1: "./Images/Tactics/40117.jpg", tactics2: "./Images/Tactics/40118.jpg", tactics3: "./Images/Tactics/40119.jpg", token: "./Images/Lannister/Tokens/ASOIAF-LANNISTER-ATCH-JAMIE-SLAYER.png", attachment2: "None" },
    { name: "Joffrey Baratheon", subName: "First of His Name", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Lannister/Commander-Cards/20121f.jpg", thumb: "./Images/Lannister/Thumb/P-20121b.png", tactics1: "./Images/Tactics/40123.jpg", tactics2: "./Images/Tactics/40124.jpg", tactics3: "./Images/Tactics/40125.jpg", token: "./Images/Lannister/Tokens/ASOIAF-LANNISTER-ATCH-JOFFREY.png", attachment2: "None" },
    { name: "The High Sparrow", subName: "Father of the Faithful", cost: 0, type: "NCU", unique: true, commander: true, imgFile: "./Images/Lannister/Commander-Cards/30103f.jpg", thumb: "./Images/Lannister/Thumb/P-30103b.png", tactics1: "./Images/Tactics/40120.jpg", tactics2: "./Images/Tactics/40121.jpg", tactics3: "./Images/Tactics/40122.jpg", token: "./Images/Lannister/Tokens/ASOIAF-LANNISTER-SPARROW.png"},
    { name: "Tyrion Lannister", subName: "Halfman", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Lannister/Commander-Cards/20105f.jpg", thumb: "./Images/Lannister/Thumb/P-20105b.png", tactics1: "./Images/Tactics/40111.jpg", tactics2: "./Images/Tactics/40112.jpg", tactics3: "./Images/Tactics/40113.jpg", token: "./Images/Lannister/Tokens/ASOIAF-LANNISTER-ATCH-C-TYRION.png", attachment2: "None" },
    { name: "Tywin Lannister", subName: "Lord of Casterly Rock", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Lannister/Commander-Cards/20104f.jpg", thumb: "./Images/Lannister/Thumb/P-20104b.png", tactics1: "./Images/Tactics/40114.jpg", tactics2: "./Images/Tactics/40115.jpg", tactics3: "./Images/Tactics/40116.jpg", token: "./Images/Lannister/Tokens/ASOIAF-LANNISTER-ATCH-C-TYWIN.png", attachment2: "None" }
    ]
  },
  {
    type: 'group', name: 'Stark', items: [
    { name: "Brynden Tully", subName: "The Blackfish", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Stark/Commander-Cards/20208f.jpg", tactics1: "./Images/Tactics/40217.jpg", tactics2: "./Images/Tactics/40218.jpg", tactics3: "./Images/Tactics/40219.jpg", token: "./Images/Stark/Tokens/ASOIAF-STARK-C-TULLY.png", attachment2: "None" },
    { name: "Howland Reed", subName: "Lord of the Crannogs", cost: 0, type: "NCU", unique: true, commander: true, imgFile: "./Images/Stark/Commander-Cards/30203f.jpg", tactics1: "./Images/Tactics/40223.jpg", tactics2: "./Images/Tactics/40224.jpg", tactics3: "./Images/Tactics/40225.jpg", token: "./Images/Stark/Tokens/ASOIAF-STARK-HOWLAND-REED.png" },
    { name: "Eddard Stark", subName: "Lord of Winterfell", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Stark/Commander-Cards/20210f.jpg", tactics1: "./Images/Tactics/40214.jpg", tactics2: "./Images/Tactics/40215.jpg", tactics3: "./Images/Tactics/40216.jpg", token: "./Images/Stark/Tokens/ASOIAF-STARK-EDDARD.png", attachment2: "None" },
    { name: "Greatjon Umber", subName: "Lord of Last Hearth", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Stark/Commander-Cards/20202f.jpg", token: "./Images/Stark/Tokens/ASOIAF-STARK-ATCH-C-GREATJON.png", tactics1: "./Images/Tactics/40208.jpg", tactics2: "./Images/Tactics/40209.jpg", tactics3: "./Images/Tactics/40210.jpg", attachment2: "None" },
    { name: "Robb Stark", subName: "The Wolf Lord", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Stark/Commander-Cards/20201f.jpg", tactics1: "./Images/Tactics/40220.jpg", tactics2: "./Images/Tactics/40221.jpg", tactics3: "./Images/Tactics/40222.jpg", token: "./Images/Stark/Tokens/ASOIAF-STARK-ATCH-C-ROBB.png", attachment2: "None" },
    { name: "Rodrik Cassel", subName: "Master-at-Arms", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Stark/Commander-Cards/20211f.jpg", tactics1: "./Images/Tactics/40226.jpg", tactics2: "./Images/Tactics/40227.jpg", tactics3: "./Images/Tactics/40228.jpg", token: "./Images/Stark/Tokens/ASOIAF-STARK-RODRIK.png", attachment2: "None" },
    { name: "Brynden Tully", subName: "Outrider Commander", KS: true, cost: 0, type: "Cavalry", unique: true, commander: true, imgFile: "./Images/Stark/Commander-Cards/20215f.jpg", tactics1: "./Images/Tactics/40211.jpg", tactics2: "./Images/Tactics/40212.jpg", tactics3: "./Images/Tactics/40213.jpg", token: "./Images/Stark/Tokens/ASOIAF-STARK-C-TULLY.png", attachment2: "None" },
    ]
  },
  {
    type: 'group', name: 'Nights Watch', items: [
    { name: "Alliser Thorne", subName: "Master-at-Arms", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/NightsWatch/Commander-Cards/20509f.jpg", tactics1: "./Images/Tactics/40514.jpg", tactics2: "./Images/Tactics/40515.jpg", tactics3: "./Images/Tactics/40516.jpg", token: "./Images/NightsWatch/Tokens/ASOIAF-NW-THORNE.png", attachment2: "None" },
    { name: "Othell Yarwyck", subName: "First Builder", cost: 0, type: "NCU", unique: true, commander: true, imgFile: "./Images/NightsWatch/Commander-Cards/30505f.jpg", tactics1: "./Images/Tactics/40520.jpg", tactics2: "./Images/Tactics/40521.jpg", tactics3: "./Images/Tactics/40522.jpg", token: "./Images/NightsWatch/Tokens/ASOIAF-NW-YARWYCK.png" },
    { name: "Donal Noye", subName: "Defender of Castle Black", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/NightsWatch/Commander-Cards/20511f.jpg", tactics1: "./Images/Tactics/40517.jpg", tactics2: "./Images/Tactics/40518.jpg", tactics3: "./Images/Tactics/40519.jpg", token: "./Images/NightsWatch/Tokens/ASOIAF-NW-NOYE.png", attachment2: "None" },
    { name: "Jeor Mormont", subName: "997th Lord Commander", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/NightsWatch/Commander-Cards/20501f.jpg", tactics1: "./Images/Tactics/40508.jpg", tactics2: "./Images/Tactics/40509.jpg", tactics3: "./Images/Tactics/40510.jpg", token: "./Images/NightsWatch/Tokens/ASOIAF-NW-JEOR.png", attachment2: "None" },
    { name: "Jon Snow", subName: "998th Lord Commander", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/NightsWatch/Commander-Cards/20502f.jpg", tactics1: "./Images/Tactics/40511.jpg", tactics2: "./Images/Tactics/40512.jpg", tactics3: "./Images/Tactics/40513.jpg", token: "./Images/NightsWatch/Tokens/ASOIAF-NW-JON.png", attachment2: "None" },
    ]
  },
  {
    type: 'group', name: 'Free Folk', items: [
    { name: "Harma", subName: "Vanguard Commander", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/FreeFolk/Commander-Cards/20317f.jpg", tactics1: "./Images/Tactics/40320.jpg", tactics2: "./Images/Tactics/40321.jpg", tactics3: "./Images/Tactics/40322.jpg", token: "./Images/FreeFolk/Tokens/ASOIAF-FF-HARMA.png", attachment2: {name: "Harma's Bannerman", cost: 0, type: "Infantry", unique: true, imgFile: "./Images/FreeFolk/Attachment-Cards/20319f.jpg"} },
    { name: "Mance Rayder", subName: "King Beyond the Wall", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/FreeFolk/Commander-Cards/20303f.jpg", tactics1: "./Images/Tactics/40314.jpg", tactics2: "./Images/Tactics/40315.jpg", tactics3: "./Images/Tactics/40316.jpg", token: "./Images/FreeFolk/Tokens/ASOIAF-FF-C-RAYDER.png", attachment2: "None" },
    { name: "Rattleshirt", subName: "The Lord of Bones", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/FreeFolk/Commander-Cards/20315f.jpg", tactics1: "./Images/Tactics/40317.jpg", tactics2: "./Images/Tactics/40318.jpg", tactics3: "./Images/Tactics/40319.jpg", token: "./Images/FreeFolk/Tokens/ASOIAF-FF-RATTLESHIRT.png", attachment2: "None" },
    { name: "Styr", subName: "Magnar Of Thenn", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/FreeFolk/Commander-Cards/20313f.jpg", tactics1: "./Images/Tactics/40326.jpg", tactics2: "./Images/Tactics/40327.jpg", tactics3: "./Images/Tactics/40328.jpg", token: "./Images/FreeFolk/Tokens/ASOIAF-FF-STYR.png", attachment2: "None" },
    { name: "The Weeper", subName: "Horrific Butcher", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/FreeFolk/Commander-Cards/20320f.jpg", tactics1: "./Images/Tactics/40323.jpg", tactics2: "./Images/Tactics/40324.jpg", tactics3: "./Images/Tactics/40325.jpg", token: "./Images/FreeFolk/Tokens/ASOIAF-FF-WEEPER.png", attachment2: "None" },
    { name: "Tormund Giantsbane", subName: "Thunderfist", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/FreeFolk/Commander-Cards/20301f.jpg", tactics1: "./Images/Tactics/40311.jpg", tactics2: "./Images/Tactics/40312.jpg", tactics3: "./Images/Tactics/40313.jpg", token: "./Images/FreeFolk/Tokens/ASOIAF-FF-C-TORMUND.png", attachment2: "None" },
    ]
  },
  {
    type: 'group', name: 'Baratheon', items: [
    { name: "Andrew Estermont", subName: "First of The King's Men", Loyalty: "Stannis Baratheon", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Baratheon/Commander-Cards/20610f.jpg", tactics1: "./Images/Tactics/40618.jpg", tactics2: "./Images/Tactics/40619.jpg", tactics3: "./Images/Tactics/40620.jpg", token: "", attachment2: "None" },
    { name: "Axell Florent", subName: "First of the Queen's Men", Loyalty: "Stannis Baratheon", cost: 0, type: "NCU", unique: true, commander: true, imgFile: "./Images/Baratheon/Commander-Cards/30607f.jpg", tactics1: "./Images/Tactics/40624.jpg", tactics2: "./Images/Tactics/40625.jpg", tactics3: "./Images/Tactics/40626.jpg", token: "", attachment2: "None" },
    { name: "Cortnay Penrose", subName: "Castellan of Storm's End", Loyalty: "Renly Baratheon", cost: 0, type: "NCU", unique: true, commander: true, imgFile: "./Images/Baratheon/Commander-Cards/30611f.jpg", tactics1: "./Images/Tactics/40636.jpg", tactics2: "./Images/Tactics/40637.jpg", tactics3: "./Images/Tactics/40638.jpg", token: "", attachment2: "None" },
    { name: "Davos Seaworth", subName: "Hero of Blackwater", Loyalty: "Stannis Baratheon", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Baratheon/Commander-Cards/20607f.jpg", tactics1: "./Images/Tactics/40614.jpg", tactics2: "./Images/Tactics/40615.jpg", tactics3: "./Images/Tactics/40616.jpg", tactics4: "./Images/Tactics/40617.jpg",  token: "", attachment2: "None" },
    { name: "Eldon Estermont", subName: "Lord of Greenstone", Loyalty: "Renly Baratheon", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Baratheon/Commander-Cards/20615f.jpg", tactics1: "./Images/Tactics/40633.jpg", tactics2: "./Images/Tactics/40634.jpg", tactics3: "./Images/Tactics/40635.jpg", token: "", attachment2: "None" },
    { name: "Loras Tyrell", subName: "The Knight of Flowers", Loyalty: "Renly Baratheon", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Baratheon/Commander-Cards/20612f.jpg", tactics1: "./Images/Tactics/40630.jpg", tactics2: "./Images/Tactics/40631.jpg", tactics3: "./Images/Tactics/40632.jpg", token: "", attachment2: "None" },
    { name: "Renly Baratheon", subName: "The Charismatic Heir", Loyalty: "Renly Baratheon", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Baratheon/Commander-Cards/20601f.jpg", tactics1: "./Images/Tactics/40611.jpg", tactics2: "./Images/Tactics/40612.jpg", tactics3: "./Images/Tactics/40613.jpg", token: "", attachment2: "None" },
    { name: "Renly Baratheon", subName: "Lord Paramount of the Stormlands", Loyalty: "Renly Baratheon", cost: 0, type: "Infantry", commander: true, unique: true, imgFile: "./Images/Baratheon/Commander-Cards/20611f.jpg", tactics1: "./Images/Tactics/40627.jpg", tactics2: "./Images/Tactics/40628.jpg", tactics3: "./Images/Tactics/40629.jpg", token: "", attachment2: "None" },
    { name: "Stannis Baratheon", subName: "The Rightful Heir", Loyalty: "Stannis Baratheon", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Baratheon/Commander-Cards/20602f.jpg", tactics1: "./Images/Tactics/40608.jpg", tactics2: "./Images/Tactics/40609.jpg", tactics3: "./Images/Tactics/40610.jpg", token: "", attachment2: "None" },
    { name: "Stannis Baratheon", subName: "The One True King", Loyalty: "Stannis Baratheon", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Baratheon/Commander-Cards/20605f.jpg", tactics1: "./Images/Tactics/40621.jpg", tactics2: "./Images/Tactics/40622.jpg", tactics3: "./Images/Tactics/40623.jpg", token: "", attachment2: "None" },
    ]
  },
  {
    type: 'group', name: 'Targaryen', items: [
    { name: "Barristan Selmy", subName: "Barristan The Bold", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Targaryen/Commander-Cards/20707f.jpg", tactics1: "./Images/Tactics/40714.jpg", tactics2: "./Images/Tactics/40715.jpg", tactics3: "./Images/Tactics/40716.jpg", token: "", attachment2: "None"},
    { name: "Belwas", subName: "The Strong", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Targaryen/Commander-Cards/20711f.jpg", tactics1: "./Images/Tactics/40717.jpg", tactics2: "./Images/Tactics/40718.jpg", tactics3: "./Images/Tactics/40719.jpg", token: "", attachment2: "None" },
    { name: "Grey Worm", subName: "Unsullied Commander", cost: 0, type: "Infantry", unique: true, commander: true, imgFile: "./Images/Targaryen/Commander-Cards/20712f.jpg", tactics1: "./Images/Tactics/40720.jpg", tactics2: "./Images/Tactics/40721.jpg", tactics3: "./Images/Tactics/40722.jpg", token: "", attachment2: "None" },
    { name: "Jorah Mormont", subName: "Westerosi Tactician", cost: 0, type: "Cavalry", unique: true, commander: true, imgFile: "./Images/Targaryen/Commander-Cards/20702f.jpg", tactics1: "./Images/Tactics/40711.jpg", tactics2: "./Images/Tactics/40712.jpg", tactics3: "./Images/Tactics/40713.jpg", token: "", attachment2: "None" },
    { name: "Khal Drogo", subName: "The Great Khal", cost: 0, type: "Cavalry", unique: true, commander: true, imgFile: "./Images/Targaryen/Commander-Cards/20701f.jpg", tactics1: "./Images/Tactics/40708.jpg", tactics2: "./Images/Tactics/40709.jpg", tactics3: "./Images/Tactics/40710.jpg", token: "", attachment2: "None" },
    ]
  },
]

  export default commanders;